title: Matthew Aitchison # your name (or website title) here
logo: "/images/Photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am recent graduate with a masters degree in Applied Data Science and Statistics from the University of Exeter.
  During my undergraduate sudying mathematics, I had a particular focus on statistics.
  <br><br>
  I am currently persuing a career in data science within techology or business organisations.
  <br><br>
  <a href="https://www.linkedin.com/in/matthew-aitchison-10b40a157">View My LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/MWAitchison">View My GitHub Profile</a> 
  
  <a href="https://www.kaggle.com/matthewaitchison"> View My Kaggle Profile </a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
